package com.asproaca.asproaca.modelos

data class Finca(
    val idFinca: String? = null,
    val idUsuario: String? = null,
    val encargadoRegistro: String? = null,
    var estadoActualizar: Boolean? = null,
    val nombre_finca: String? = null,
    val coordenada_x: String? = null,
    val coordenada_y: String? = null,
    val vereda_finca: String? = null,
    val zona: String? = null,
    val municipio: String? = null,
    val antiguedad_finca: String? = null,
    val historia_finca: String? = null,
    val realiza_quema: String? = null,
    val creado: String? = null,
    val certificaciones: String? = null,
    val zona_riesgo: String? = null,
    val tenencia_de_la_tierra: String? = null,
    val area_total: String? = null,
    val datos_casa: Casa? = null,
    val datos_sociales: DatosSociales? = null,
    val datos_productivos: MutableList<Productivos>? = null,
    val datos_animal: MutableList<Animales>? = null,
    val datos_trabajadores: DatosTrabajadorres? = null,
    val datos_ambientales: DatosAmbientales? = null,
    val modificaciones_fincas:MutableList<String>? = null,
    val idFincaPadre:String? = null,
    var estadoModificar: Boolean? = null,
)
